// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Ficha5_B0Cf7C9Cb72665A5Af393B65C08F51A44 {
    valores: { [key: string]: string };
    campos: Campo[];
}

export interface Campo {
    funcion: string;
    campo: string;
}
