// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Ficha7_1Fc880Afd2Dbb32A1E4Dc8Bc08F51Fb5 {
    valores: Valores;
    campos: Campo[];
}

export interface Campo {
    funcion: string;
    campo: string;
}

export interface Valores {
    archivo3: string;
    rbd: string;
    archivo2: string;
    archivo1: string;
    archivo4: string;
}
