// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface Ficha5_B0Cf7C9Cb72665A5Af393B65C08F51A43 {
    valores: Valores;
    campos: Campo[];
}

export interface Campo {
    funcion: string;
    campo: string;
}

export interface Valores {
    tiene_informe_visita_2017: string;
    tiene_informe_visita_2018: string;
    tiene_informe_visita_2019_t: string;
    tiene_informe_visita_2019_im: string;
    tiene_informe_visita_2019_i: string;
    dl_rbd: string;
    tiene_informe_visita_2020: string;
}
