// Generated by https://quicktype.io

export interface TopLevel {
    valores: { [key: string]: string };
    campos:  Campo[];
}

export interface Campo {
    funcion: string;
    campo:   string;
}
